apiVersion: v1
kind: Service
metadata:
  name: {{ include "deviceapi.fullname" . }}
  labels:
{{ include "deviceapi.labels" . | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "deviceapi.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
  type: {{ .Values.service.type }}
