apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include (printf "%s.fullname" .Chart.Name) . }}-config
  labels: {{ include (printf "%s.labels" .Chart.Name) . | nindent 4 }}
data: {{- (.Files.Glob "config/*.yml").AsConfig | nindent 2 }}