# Default values for deviceapi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: sin.ocir.io/testing/device-api
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: 2.0.0
  pullSecret: docker-registry

dbtools:
  repository: sin.ocir.io/testing/dbtools
  tag: 1.0.1
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

env:
  javaOpts: -Xms32m -Xmx150m -XX:MaxRAM=150m -XX:+UnlockExperimentalVMOptions -XX:+UseZGC
  springProfilesActive: dev
  springConfigLocation: /config/

secrets:
  oadbUserSecret: #oadb-deviceapi

service:
  type: ClusterIP  #LoadBalancer
  targetPort: 8080
  port: 80
  protocol: TCP

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8080
  initialDelaySeconds: 90
  periodSeconds: 15
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
  initialDelaySeconds: 90
  periodSeconds: 15
  failureThreshold: 5

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podSecurityContext: {}
  # fsGroup: 2000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
