spring:
  config:
    activate:
      on-profile: dev
  application:
    name: device-api
  server:
    port: 8080
  datasource:
    url: jdbc:oracle:thin:@{oadbService}?TNS_ADMIN=/wallet
    username:
    password:
  jpa:
    database: oracle
    hibernate:
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
      show-sql: true
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
logging:
  level:
    com:
      vs:
        device: DEBUG
oci:
  tenant:
    region: {ociRegion}
    adb-username-ocid: {adbUsername}
    adb-password-ocid: {adbPassword}
    stream-ocid:
    message-endpoint:
    topic-ocid:
